/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.persistence.*;
import javax.swing.*;

/**
 *
 * @author Huawei
 */
public class UbahPassword extends javax.swing.JFrame {

    /**
     * Creates new form Password
     */
    public UbahPassword() {
        initComponents();
        LblPsw.setVisible(false);
        BtnUbah.setVisible(false);
        TxtPw.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblPsw = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        TxtPw = new javax.swing.JTextField();
        BtnCari = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        LblBack = new javax.swing.JLabel();
        LblSecurityQuestion = new javax.swing.JLabel();
        CbSecurityQuestion = new javax.swing.JComboBox<>();
        LblAnswer = new javax.swing.JLabel();
        TxtAnswer = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel1.setText("UBAH PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel2.setText("Username             :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        LblPsw.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        LblPsw.setText("Password              :");
        getContentPane().add(LblPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 199, -1));

        TxtPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPwActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 201, -1));

        BtnCari.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        BtnCari.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei\\Documents\\NetBeansProjects\\Cafe Management System\\src\\images\\search.png")); // NOI18N
        BtnCari.setText("SEARCH");
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        BtnUbah.setBackground(new java.awt.Color(255, 255, 0));
        BtnUbah.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        BtnUbah.setForeground(new java.awt.Color(255, 255, 255));
        BtnUbah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei\\Documents\\NetBeansProjects\\Cafe Management System\\src\\images\\change Password.png")); // NOI18N
        BtnUbah.setText("UBAH");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        LblBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei\\Documents\\NetBeansProjects\\Cafe Management System\\src\\images\\exit.png")); // NOI18N
        LblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblBackMouseClicked(evt);
            }
        });
        getContentPane().add(LblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        LblSecurityQuestion.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        LblSecurityQuestion.setText("Security Question :");
        getContentPane().add(LblSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        CbSecurityQuestion.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        CbSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Security Question", "Arah mana Anda tidur?", "Siapa nama mantan terindah Anda?", "Dimana restoran favorit Anda?", "Apa yang Anda lakukan saat stres?", " " }));
        getContentPane().add(CbSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 200, -1));

        LblAnswer.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        LblAnswer.setText("Answer                  :");
        getContentPane().add(LblAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(TxtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        if (TxtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username dulu!");
        } else {
            BtnCari.doClick();
        }
    }//GEN-LAST:event_TxtUserActionPerformed

    private void LblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBackMouseClicked
        Login y = new Login();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblBackMouseClicked

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        if (TxtUser.getText().equals("")
                | CbSecurityQuestion.getSelectedIndex() == 0
                | TxtAnswer.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = TxtUser.getText();
            String security = (String) CbSecurityQuestion.getSelectedItem();
            String answer = TxtAnswer.getText();
            
            Login_1 y = em.find(Login_1.class, user);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                TxtUser.requestFocus();
            } else {
                LblPsw.setVisible(true);
                BtnUbah.setVisible(true);
                TxtPw.setVisible(true);
                TxtUser.setEditable(false);
                CbSecurityQuestion.setEditable(false);
                TxtAnswer.setEditable(false);
                TxtPw.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnCariActionPerformed

    private void TxtPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPwActionPerformed
        BtnUbah.doClick();
    }//GEN-LAST:event_TxtPwActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        if (TxtPw.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Cari Terlebih Dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();

            String user, pw, security, answer;
            user = TxtUser.getText();
            security = (String) CbSecurityQuestion.getSelectedItem();
            answer = TxtAnswer.getText();
            pw = TxtPw.getText();
            
            Login_1 x = em.find(Login_1.class, user);
            x.setUsername(user);
            x.setSecurityQuestion(security);
            x.setAnswer(answer);
            x.setPassword(pw);
            em.persist(x);

            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Berhasil diubah");

            em.close();
            emf.close();

            Login y = new Login();
            y.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BtnUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbahPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox<String> CbSecurityQuestion;
    private javax.swing.JLabel LblAnswer;
    private javax.swing.JLabel LblBack;
    private javax.swing.JLabel LblPsw;
    private javax.swing.JLabel LblSecurityQuestion;
    private javax.swing.JTextField TxtAnswer;
    private javax.swing.JTextField TxtPw;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
